name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y jmeter

      - name: Run JMeter Test
        run: |
          jmeter -n -t test-plan-shopizer.jmx -l results/test-results.jtl

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/test-results.jtl
